model: facebook/wav2vec2-base

dataset: LIUM/tedlium

backend_config:
  client_resources:
    num_cpus: 8
gpu_backend_config:
  client_resources: 
    num_gpus: 1

clients:
  - cpu_time: 30
  - cpu_time: 20
  - cpu_time: 10

partitions: 10
