firebase_database_url: https://ondevicetraining-dc6d0-default-rtdb.firebaseio.com/
model_use: https://github.com/MatheusDCasanova/OnDeviceTraning/raw/refs/heads/master/model_mnist_fixed_batch_size.tflite
device_config_path: /home/tobias/flower-simulation/deviceConfigurations.json
simulation_result_path: /home/tobias/flower-simulation/simulation-result.csv

partitions: 300
min_client_per_round: 2
num_rounds: 3

backend_config:
  client_resources:
    num_cpus: 8
gpu_backend_config:
  client_resources: 
    num_gpus: 1
