model: prajjwal1/bert-tiny

dataset: stanfordnlp/imdb

backend_config:
  client_resources:
    num_cpus: 8
gpu_backend_config:
  client_resources: 
    num_gpus: 1

clients:
  - energy: 50
    epochs: 2
  - energy: 114
    epochs: 2

partitions: 10
